/*
 * tuntun
 */
package projects;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.*;

/**
 *
 * @author tunkuki
 */
public class Adminn extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public Adminn() {
        initComponents();
        addPlaceholderStyle(searchBar);
        removePlaceholderStyle(searchBar);
        jSeparator1.setBackground(new Color(238,238,238));
        jSeparator2.setBackground(new Color(238,238,238));
        JScrollPane scrollpane = new JScrollPane(cTopPane);
        scrollpane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        JButton [] btns = {jButton1,jButton4,jButton10,jButton9,jButton11,jButton12,jButton13,jButton14,jButton15,jButton16,jButton8};
        for (JButton btn : btns){
            btn.setUI(new BasicButtonUI());
            btn.setBackground(new Color(255,255,255));
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    if (e.getSource().equals(btn)){
                        btn.setBackground(Color.LIGHT_GRAY);
                    }
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setForeground(Color.black);
                    btn.setBackground(new Color(255,255,255));
                }
            });
        } 
    }

    private void addPlaceholderStyle(JTextField searchBar){
        Font font = searchBar.getFont();
        font = font.deriveFont(Font.ITALIC);
        searchBar.setFont(font);
        searchBar.setForeground(Color.gray);
    }
    
    private void removePlaceholderStyle(JTextField searchBar){
        Font font = searchBar.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        searchBar.setFont(font);
        searchBar.setForeground(Color.GRAY);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        topSidePane = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        sp2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        rightPane = new javax.swing.JPanel();
        rTopPane = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        searchBar = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        cTopPane = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        roundedButton1 = new projects.RoundedButton();
        jLabel7 = new javax.swing.JLabel();
        roundedButton2 = new projects.RoundedButton();
        jLabel8 = new javax.swing.JLabel();
        roundedButton3 = new projects.RoundedButton();
        jLabel9 = new javax.swing.JLabel();
        roundedButton4 = new projects.RoundedButton();
        jLabel10 = new javax.swing.JLabel();
        roundedButton5 = new projects.RoundedButton();
        jLabel11 = new javax.swing.JLabel();
        roundedButton6 = new projects.RoundedButton();
        jLabel12 = new javax.swing.JLabel();
        roundedButton7 = new projects.RoundedButton();
        jLabel15 = new javax.swing.JLabel();
        roundedButton8 = new projects.RoundedButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        sidePane.setBackground(new java.awt.Color(255, 255, 255));
        sidePane.setPreferredSize(new java.awt.Dimension(243, 834));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(238, 238, 233));
        jPanel4.setPreferredSize(new java.awt.Dimension(1, 500));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        sidePane.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, 760));

        topSidePane.setBackground(new java.awt.Color(255, 255, 255));
        topSidePane.setPreferredSize(new java.awt.Dimension(243, 146));
        topSidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Ayuthaya", 1, 16)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/images/Do 1 (1).png"))); // NOI18N
        jButton4.setText(" DooWai");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        topSidePane.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 60));

        sidePane.add(topSidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        sp2.setBackground(new java.awt.Color(255, 255, 255));
        sp2.setPreferredSize(new java.awt.Dimension(243, 60));
        sp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Ayuthaya", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/images/settings2.png"))); // NOI18N
        jButton1.setText("  Admin Control");
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sp2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 40));

        sidePane.add(sp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 156, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(243, 365));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setFont(new java.awt.Font("Ayuthaya", 1, 13)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/images/1828427 1.png"))); // NOI18N
        jButton10.setText("  Logout");
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 40));

        sidePane.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 463, -1, -1));

        jPanel1.add(sidePane, java.awt.BorderLayout.WEST);

        rightPane.setPreferredSize(new java.awt.Dimension(951, 834));
        rightPane.setLayout(new java.awt.BorderLayout());

        rTopPane.setBackground(new java.awt.Color(255, 255, 255));
        rTopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        rTopPane.setMaximumSize(new java.awt.Dimension(951, 148));
        rTopPane.setMinimumSize(new java.awt.Dimension(951, 148));
        rTopPane.setPreferredSize(new java.awt.Dimension(951, 148));
        rTopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/images/1144760 2.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        rTopPane.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 50, 40));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/images/image 3.png"))); // NOI18N
        jButton13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        rTopPane.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, -1, -1));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/images/image 2.png"))); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rTopPane.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 112, 20, 20));

        jSeparator1.setBackground(new java.awt.Color(238, 238, 233));
        jSeparator1.setForeground(new java.awt.Color(238, 238, 233));
        jSeparator1.setPreferredSize(new java.awt.Dimension(951, 10));
        rTopPane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(238, 238, 233));
        jSeparator2.setForeground(new java.awt.Color(238, 238, 233));
        jSeparator2.setPreferredSize(new java.awt.Dimension(951, 10));
        rTopPane.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        searchBar.setForeground(new java.awt.Color(204, 204, 204));
        searchBar.setText("Search for something");
        searchBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchBarFocusLost(evt);
            }
        });
        searchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBarMouseExited(evt);
            }
        });
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });
        rTopPane.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 115, 400, -1));

        jButton9.setBackground(new java.awt.Color(239, 239, 239));
        jButton9.setFont(new java.awt.Font("Ayuthaya", 1, 13)); // NOI18N
        jButton9.setText("Admin Control");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        rTopPane.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, 30));

        jButton14.setBackground(new java.awt.Color(239, 239, 239));
        jButton14.setFont(new java.awt.Font("Ayuthaya", 1, 13)); // NOI18N
        jButton14.setText("Action");
        jButton14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        rTopPane.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, 30));

        jButton16.setBackground(new java.awt.Color(239, 239, 239));
        jButton16.setFont(new java.awt.Font("Ayuthaya", 1, 13)); // NOI18N
        jButton16.setText("ชื่อการ์ตูน");
        jButton16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        rTopPane.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 110, 30));

        jButton15.setBackground(new java.awt.Color(239, 239, 239));
        jButton15.setFont(new java.awt.Font("Ayuthaya", 1, 13)); // NOI18N
        jButton15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jButton15.setLabel("รูปการ์ตูน");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        rTopPane.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 110, 30));

        rightPane.add(rTopPane, java.awt.BorderLayout.NORTH);

        cTopPane.setBackground(new java.awt.Color(255, 255, 255));
        cTopPane.setMaximumSize(new java.awt.Dimension(951, 148));
        cTopPane.setMinimumSize(new java.awt.Dimension(951, 148));
        cTopPane.setPreferredSize(new java.awt.Dimension(951, 834));
        cTopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(239, 239, 239));
        jButton8.setFont(new java.awt.Font("Ayuthaya", 1, 13)); // NOI18N
        jButton8.setText("ชื่อการ์ตูน");
        jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        cTopPane.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 30));

        roundedButton1.setBackground(new java.awt.Color(42, 104, 20));
        roundedButton1.setToolTipText("");
        roundedButton1.setRoundBottomLeft(15);
        roundedButton1.setRoundBottomRight(15);
        roundedButton1.setRoundTopLeft(15);
        roundedButton1.setRoundTopRight(15);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EDIT");

        javax.swing.GroupLayout roundedButton1Layout = new javax.swing.GroupLayout(roundedButton1);
        roundedButton1.setLayout(roundedButton1Layout);
        roundedButton1Layout.setHorizontalGroup(
            roundedButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedButton1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        roundedButton1Layout.setVerticalGroup(
            roundedButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedButton1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        cTopPane.add(roundedButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 80, 30));

        roundedButton2.setBackground(new java.awt.Color(200, 57, 57));
        roundedButton2.setToolTipText("");
        roundedButton2.setRoundBottomLeft(15);
        roundedButton2.setRoundBottomRight(15);
        roundedButton2.setRoundTopLeft(15);
        roundedButton2.setRoundTopRight(15);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DELETE");

        javax.swing.GroupLayout roundedButton2Layout = new javax.swing.GroupLayout(roundedButton2);
        roundedButton2.setLayout(roundedButton2Layout);
        roundedButton2Layout.setHorizontalGroup(
            roundedButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedButton2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        roundedButton2Layout.setVerticalGroup(
            roundedButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedButton2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        cTopPane.add(roundedButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 80, 30));

        roundedButton3.setBackground(new java.awt.Color(42, 104, 20));
        roundedButton3.setToolTipText("");
        roundedButton3.setRoundBottomLeft(15);
        roundedButton3.setRoundBottomRight(15);
        roundedButton3.setRoundTopLeft(15);
        roundedButton3.setRoundTopRight(15);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EDIT");

        javax.swing.GroupLayout roundedButton3Layout = new javax.swing.GroupLayout(roundedButton3);
        roundedButton3.setLayout(roundedButton3Layout);
        roundedButton3Layout.setHorizontalGroup(
            roundedButton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedButton3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        roundedButton3Layout.setVerticalGroup(
            roundedButton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedButton3Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        cTopPane.add(roundedButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 80, 30));

        roundedButton4.setBackground(new java.awt.Color(200, 57, 57));
        roundedButton4.setToolTipText("");
        roundedButton4.setRoundBottomLeft(15);
        roundedButton4.setRoundBottomRight(15);
        roundedButton4.setRoundTopLeft(15);
        roundedButton4.setRoundTopRight(15);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DELETE");

        javax.swing.GroupLayout roundedButton4Layout = new javax.swing.GroupLayout(roundedButton4);
        roundedButton4.setLayout(roundedButton4Layout);
        roundedButton4Layout.setHorizontalGroup(
            roundedButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedButton4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        roundedButton4Layout.setVerticalGroup(
            roundedButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedButton4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        cTopPane.add(roundedButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 80, 30));

        roundedButton5.setBackground(new java.awt.Color(42, 104, 20));
        roundedButton5.setToolTipText("");
        roundedButton5.setRoundBottomLeft(15);
        roundedButton5.setRoundBottomRight(15);
        roundedButton5.setRoundTopLeft(15);
        roundedButton5.setRoundTopRight(15);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("EDIT");

        javax.swing.GroupLayout roundedButton5Layout = new javax.swing.GroupLayout(roundedButton5);
        roundedButton5.setLayout(roundedButton5Layout);
        roundedButton5Layout.setHorizontalGroup(
            roundedButton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedButton5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        roundedButton5Layout.setVerticalGroup(
            roundedButton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedButton5Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        cTopPane.add(roundedButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 80, 30));

        roundedButton6.setBackground(new java.awt.Color(200, 57, 57));
        roundedButton6.setToolTipText("");
        roundedButton6.setRoundBottomLeft(15);
        roundedButton6.setRoundBottomRight(15);
        roundedButton6.setRoundTopLeft(15);
        roundedButton6.setRoundTopRight(15);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DELETE");

        javax.swing.GroupLayout roundedButton6Layout = new javax.swing.GroupLayout(roundedButton6);
        roundedButton6.setLayout(roundedButton6Layout);
        roundedButton6Layout.setHorizontalGroup(
            roundedButton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedButton6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        roundedButton6Layout.setVerticalGroup(
            roundedButton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedButton6Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        cTopPane.add(roundedButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 80, 30));

        roundedButton7.setBackground(new java.awt.Color(42, 104, 20));
        roundedButton7.setToolTipText("");
        roundedButton7.setRoundBottomLeft(15);
        roundedButton7.setRoundBottomRight(15);
        roundedButton7.setRoundTopLeft(15);
        roundedButton7.setRoundTopRight(15);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EDIT");

        javax.swing.GroupLayout roundedButton7Layout = new javax.swing.GroupLayout(roundedButton7);
        roundedButton7.setLayout(roundedButton7Layout);
        roundedButton7Layout.setHorizontalGroup(
            roundedButton7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedButton7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        roundedButton7Layout.setVerticalGroup(
            roundedButton7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedButton7Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        cTopPane.add(roundedButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 80, 30));

        roundedButton8.setBackground(new java.awt.Color(200, 57, 57));
        roundedButton8.setToolTipText("");
        roundedButton8.setRoundBottomLeft(15);
        roundedButton8.setRoundBottomRight(15);
        roundedButton8.setRoundTopLeft(15);
        roundedButton8.setRoundTopRight(15);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DELETE");

        javax.swing.GroupLayout roundedButton8Layout = new javax.swing.GroupLayout(roundedButton8);
        roundedButton8.setLayout(roundedButton8Layout);
        roundedButton8Layout.setHorizontalGroup(
            roundedButton8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedButton8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel16)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        roundedButton8Layout.setVerticalGroup(
            roundedButton8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedButton8Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        cTopPane.add(roundedButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 80, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("รูปการ์ตูน");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setMaximumSize(new java.awt.Dimension(55, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(55, 20));
        cTopPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 190, 250));

        jLabel1.setText("#1");
        cTopPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setText("#2");
        cTopPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("รูปการ์ตูน");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setMaximumSize(new java.awt.Dimension(55, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(55, 20));
        cTopPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 190, 250));

        jLabel14.setText("#3");
        cTopPane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("รูปการ์ตูน");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setMaximumSize(new java.awt.Dimension(55, 20));
        jLabel13.setMinimumSize(new java.awt.Dimension(55, 20));
        cTopPane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 190, 250));

        jLabel6.setText("#4");
        cTopPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("รูปการ์ตูน");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setMaximumSize(new java.awt.Dimension(55, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(55, 20));
        cTopPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 190, 250));

        rightPane.add(cTopPane, java.awt.BorderLayout.CENTER);

        jPanel1.add(rightPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void searchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBarFocusGained
        if (searchBar.getText().equals("Search for something")) {
            searchBar.setText(null);
            searchBar.requestFocus();
            removePlaceholderStyle(searchBar);
        }
    }//GEN-LAST:event_searchBarFocusGained

    private void searchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBarFocusLost
        if (searchBar.getText().length()==0) {
            addPlaceholderStyle(searchBar);
            searchBar.setText("Search for something");
        }
    }//GEN-LAST:event_searchBarFocusLost

    private void searchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseClicked
        //        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_searchBarMouseClicked

    private void searchBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseExited

    }//GEN-LAST:event_searchBarMouseExited

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        //        searchFilter(searchBar.getText());
    }//GEN-LAST:event_searchBarKeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cTopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel rTopPane;
    private javax.swing.JPanel rightPane;
    private projects.RoundedButton roundedButton1;
    private projects.RoundedButton roundedButton2;
    private projects.RoundedButton roundedButton3;
    private projects.RoundedButton roundedButton4;
    private projects.RoundedButton roundedButton5;
    private projects.RoundedButton roundedButton6;
    private projects.RoundedButton roundedButton7;
    private projects.RoundedButton roundedButton8;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel sidePane;
    private javax.swing.JPanel sp2;
    private javax.swing.JPanel topSidePane;
    // End of variables declaration//GEN-END:variables
}
